updated gradle and ci yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,7 +44,33 @@ jobs:
           BINTRAY_USER: jenkins-reform-hmcts
           BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
           RELEASE_VERSION: ${{ github.ref }}
-        run: ./gradlew bintrayUpload --info
+      - name: Trigger Build in JitPack
+        run: |
+          echo "Triggering JitPack build"
+
+          PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
+          PACKAGES_FILE="packages.txt"
+
+          touch ${PACKAGES_FILE}
+
+          # Try the URL 3 times before failing
+          count=1
+          until [[ $count -gt 3 ]] || [[ $(cat ${PACKAGES_FILE} | wc -l | xargs ) -gt 1 ]] ; do
+          echo "Attempt ${count}/3"
+          STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
+
+          let count+=1
+          sleep 5
+          done
+
+          echo "::group::Files Available"
+          echo $(cat ${PACKAGES_FILE})
+          echo "::endgroup::"
+
+          if [[ $count -gt 3 ]]; then
+            echo "FAILURE: ${STATUS} response from JitPack"
+            exit 1
+          fi
         if: startsWith(github.ref, 'refs/tags')
       - name: Cleanup Gradle Cache
         run: |
